package app.fuggs.document.domain;

/**
 * Indicates how a tag was added to a document.
 */
public enum TagSource
{
	/**
	 * Tag was generated by AI analysis.
	 */
	AI,

	/**
	 * Tag was added manually by a user.
	 */
	MANUAL
}
