{{- if .Values.zugferd.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.zugferd.serviceAccount.name | default (include "hopps.zugferdFullname" .) }}
  labels:
    {{- include "hopps.zugferdLabels" . | nindent 4 }}
  {{- with .Values.zugferd.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.zugferd.serviceAccount.automount }}
{{- end }}
