apiVersion: v1
kind: Service
metadata:
  name: {{ include "hopps.zugferdFullname" . }}
  labels:
    {{- include "hopps.zugferdLabels" . | nindent 4 }}
spec:
  type: {{ .Values.zugferd.service.type }}
  ports:
    - port: {{ .Values.zugferd.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "hopps.zugferdSelectorLabels" . | nindent 4 }}
