packages:
  - 'spa'
  - 'mobile'
  - 'api-client'
  - 'figma_inspo'

overrides:
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.0

allowBuilds:
  '@pact-foundation/pact-node': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  '@appthreat/sqlite3': true
  unrs-resolver: true
