packages:
  - 'spa'
  - 'mobile'
  - 'api-client'
  - 'figma_inspo'
overrides:
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.0
onlyBuiltDependencies:
  - '@pact-foundation/pact-node'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - sqlite3
  - unrs-resolver
allowBuilds:
  '@pact-foundation/pact-node': set this to true or false
  '@parcel/watcher': set this to true or false
  '@scarf/scarf': set this to true or false
  esbuild: set this to true or false
  unrs-resolver: set this to true or false
