{{- if .Values.finNarrator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.finNarrator.serviceAccount.name | default (include "hopps.finNarratorFullname" .) }}
  labels:
    {{- include "hopps.finNarratorLabels" . | nindent 4 }}
  {{- with .Values.finNarrator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.finNarrator.serviceAccount.automount }}
{{- end }}
