FROM registry.access.redhat.com/ubi8/openjdk-21:1.19

ENV LANGUAGE='en_US:en'

# Copy the JAR file
COPY target/org-1.0.1-SNAPSHOT.jar /deployments/app.jar

EXPOSE 8080
USER 185

ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

# Run the application
CMD ["java", "-jar", "/deployments/app.jar"]
