{{- if .Values.admin.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.admin.serviceAccount.name | default (include "hopps.adminFullname" .) }}
  labels:
    {{- include "hopps.adminLabels" . | nindent 4 }}
  {{- with .Values.admin.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.admin.serviceAccount.automount }}
{{- end }}
