import { Receipt } from './types';

const mockReceipts: Receipt[] = [
    {
        id: '1',
        issuer: 'Figma Inc.',
        date: '12.09.2025',
        amount: -80.0,
        category: 'IT Infrastruktur',
        status: 'paid',
        project: 'Hopps',
        bommelEmoji: '\uD83D\uDE80',
        area: 'ZWECKBETRIEB',
        purpose: 'Zweckbetrieb',
        dueDate: '10.08.2023',
        tags: ['Verein', 'MVP', 'Designwork', 'Mockups'],
        reference: 'Ipsum-123-Lorem',
        documentId: 101,
    },
    {
        id: '2',
        issuer: 'Vermieter',
        date: '01.08.2025',
        amount: -1937.67,
        category: 'Büromiete',
        status: 'unpaid',
        project: 'Open Project e.V.',
        bommelEmoji: '\uD83C\uDFE2',
        area: 'IDEELL',
        purpose: 'Hauptmietvertrag',
        dueDate: '01.08.2025',
        tags: ['Miete', 'Fixkosten', 'Langfristig'],
        reference: 'Contract-456-Miete',
        documentId: 102,
    },
    {
        id: '3',
        issuer: 'Max Muster',
        date: '03.07.2025',
        amount: 18.5,
        category: 'Reisekosten',
        status: 'draft',
        project: 'Subbommel2',
        bommelEmoji: '\uD83D\uDCCB',
        area: '',
        purpose: 'Bahnfahrt Meeting',
        dueDate: '15.07.2025',
        tags: ['Fahrtkosten', 'Bahn', 'Entwurf'],
        reference: 'RE-778-Bahn',
        documentId: null,
    },
    {
        id: '4',
        issuer: 'Figma Inc.',
        date: '10.04.2025',
        amount: -80.0,
        category: 'IT Infrastruktur',
        status: 'paid',
        project: 'Subbommel1',
        bommelEmoji: '\uD83C\uDFA8',
        area: 'ZWECKBETRIEB',
        purpose: 'Zweckbetrieb',
        dueDate: '10.08.2023',
        tags: ['Verein', 'MVP', 'Designwork', 'Mockups'],
        reference: 'Ipsum-123-Lorem',
        documentId: 104,
    },
    {
        id: '5',
        issuer: 'Stripe Inc.',
        date: '20.09.2025',
        amount: -49.99,
        category: 'Zahlungsdienstleister',
        status: 'failed',
        project: 'Kassenbuch',
        bommelEmoji: '\uD83D\uDCB0',
        area: 'WIRTSCHAFTLICH',
        purpose: 'Abgebrochene Zahlung',
        dueDate: '21.09.2025',
        tags: ['Zahlung', 'Fehlgeschlagen', 'Technisch'],
        reference: 'ERR-500-Stripe',
        documentId: null,
    },
];

export default mockReceipts;
