import { Receipt } from './types';

const mockReceipts: Receipt[] = [
    {
        id: '1',
        issuer: 'Figma Inc.',
        date: '12.09.2025',
        amount: -80.0,
        status: 'saved',
        privatelyPaid: false,
        project: 'Hopps',
        bommelEmoji: '🚀',
        purpose: 'Zweckbetrieb',
        dueDate: '10.08.2023',
        tags: ['Verein', 'MVP', 'Designwork', 'Mockups'],
        reference: 'Ipsum-123-Lorem',
        documentId: 101,
    },
    {
        id: '2',
        issuer: 'Vermieter',
        date: '01.08.2025',
        amount: -1937.67,
        status: 'saved',
        privatelyPaid: true,
        project: 'Open Project e.V.',
        bommelEmoji: '🏢',
        purpose: 'Hauptmietvertrag',
        dueDate: '01.08.2025',
        tags: ['Miete', 'Fixkosten', 'Langfristig'],
        reference: 'Contract-456-Miete',
        documentId: 102,
    },
    {
        id: '3',
        issuer: 'Max Muster',
        date: '03.07.2025',
        amount: 18.5,
        status: 'draft',
        privatelyPaid: false,
        project: 'Subbommel2',
        bommelEmoji: '📋',
        purpose: 'Bahnfahrt Meeting',
        dueDate: '15.07.2025',
        tags: ['Fahrtkosten', 'Bahn', 'Entwurf'],
        reference: 'RE-778-Bahn',
        documentId: null,
    },
    {
        id: '4',
        issuer: 'Figma Inc.',
        date: '10.04.2025',
        amount: -80.0,
        status: 'saved',
        privatelyPaid: false,
        project: 'Subbommel1',
        bommelEmoji: '🎨',
        purpose: 'Zweckbetrieb',
        dueDate: '10.08.2023',
        tags: ['Verein', 'MVP', 'Designwork', 'Mockups'],
        reference: 'Ipsum-123-Lorem',
        documentId: 104,
    },
    {
        id: '5',
        issuer: 'Stripe Inc.',
        date: '20.09.2025',
        amount: -49.99,
        status: 'saved',
        privatelyPaid: false,
        project: 'Kassenbuch',
        bommelEmoji: '💰',
        purpose: 'Monatliche Gebühr',
        dueDate: '21.09.2025',
        tags: ['Zahlung', 'Fixkosten'],
        reference: 'INV-500-Stripe',
        documentId: null,
    },
];

export default mockReceipts;
