services:
    keycloak:
        #image: quay.io/keycloak/keycloak:latest
        build: .
        container_name: keycloak
        ports:
            - "8090:8080"
        environment:
            KC_BOOTSTRAP_ADMIN_USERNAME: admin
            KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        volumes:
            - keycloak_data:/opt/keycloak/data
            #- ./dist_keycloak/keycloak-theme-for-kc-22-to-25.jar:/opt/keycloak/providers/keycloak-theme.jar
        command:
            - start-dev
            - --http-port=8080

volumes:
    keycloak_data:
# version: '2'
# services:
#     postgresql:
#         image: docker.io/bitnami/postgresql:latest
#         environment:
#             - ALLOW_EMPTY_PASSWORD=yes
#             - POSTGRESQL_USERNAME=bn_keycloak
#             - POSTGRESQL_DATABASE=bitnami_keycloak
#         volumes:
#             - 'postgresql_data:/bitnami/postgresql'
#     keycloak:
#         image: docker.io/bitnami/keycloak:latest
#         ports:
#             - '8090:8080'
#         environment:
#             - KEYCLOAK_CREATE_ADMIN_USER=true
#         depends_on:
#             - postgresql
#         volumes:
#             - ./dist_keycloak/unpacked/theme/hopps-login-theme:/opt/bitnami/keycloak/themes/hopps-login-theme
# volumes:
#     postgresql_data:
#         driver: local
