{{- if .Values.org.managementIngress.enabled -}}
{{- $fullName := include "hopps.orgFullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-management
  labels:
    {{- include "hopps.orgLabels" . | nindent 4 }}
{{- with .Values.org.managementIngress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if or (.Capabilities.APIVersions.Has "networking.k8s.io/v1/IngressClass") (.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/IngressClass") }}
  {{- if .Values.org.managementIngress.ingressClassName }}
  ingressClassName: {{ .Values.org.managementIngress.ingressClassName }}
  {{- end }}
  {{- end }}
{{- if .Values.org.managementIngress.tls }}
  tls:
  {{- range .Values.org.managementIngress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.org.managementIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - pathType: {{ .pathType }}
            path: {{ .path }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: management
          {{- end }}
  {{- end }}
{{- end }}
