apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rds.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: db-secret
    envs:
      - rds-secrets-encrypted.env
