apiVersion: v2
name: hopps
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.14

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.4"

dependencies:
  - condition: keycloak.enabled
    name: keycloakx
    # ToDo: make version controllable by dependabot
    version: 7.0.1
    repository: https://codecentric.github.io/helm-charts
    alias: keycloak
  - condition: openfgaEnabled
    name: openfga
    # ToDo: make version controllable by dependabot
    version: 0.2.16
    repository: https://openfga.github.io/helm-charts
  - condition: kafka-ui.enabled
    name: kafka-ui
    # ToDo: make version controllable by dependabot
    version: 0.7.6
    repository: https://provectus.github.io/kafka-ui-charts
  - condition: kafka.enabled
    name: kafka
    # ToDo: make version controllable by dependabot
    version: 32.4.4
    repository: https://charts.bitnami.com/bitnami
  - condition: postgresql-org.enabled
    alias: postgresqlOrg
    name: postgresql
    # ToDo: make version controllable by dependabot
    version: 16.4.5
    repository: https://charts.bitnami.com/bitnami

