name: Build hopps-app

on:
  push:
    branches: [ main, "2.0" ]
    paths:
      - 'app.hopps.hopps-app/**'
      - '.github/workflows/hopps-app.yml'
  workflow_dispatch:

defaults:
  run:
    working-directory: app.hopps.hopps-app

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -B package

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: ${{ success() }}
        uses: docker/build-push-action@v6
        with:
          context: app.hopps.hopps-app
          push: true
          file: app.hopps.hopps-app/src/main/docker/Dockerfile.jvm
          tags: ghcr.io/hopps-app/hopps-app:latest
